Repository bokzip/bokzip-android, pull requests merged in 2021-08, with the labels that each got.

#4 [feat:#2] xml 및 activity 작성
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/unionz/bokzip/DetailActivity.kt
  app/src/main/java/com/unionz/bokzip/IntroActivity.kt
  app/src/main/java/com/unionz/bokzip/MyActivity.kt
  app/src/main/java/com/unionz/bokzip/SearchResultActivity.kt
  app/src/main/java/com/unionz/bokzip/home/GeneralFragment.kt
  app/src/main/java/com/unionz/bokzip/home/MainActivity.kt
  app/src/main/java/com/unionz/bokzip/home/RecommendFragment.kt
  app/src/main/java/com/unionz/bokzip/home/ScrapFragment.kt
  app/src/main/java/com/unionz/bokzip/model/BokjiItem.kt
  app/src/main/java/com/unionz/bokzip/search/SearchActivity.kt
  app/src/main/java/com/unionz/bokzip/sign/SigninActivity.kt
  app/src/main/java/com/unionz/bokzip/sign/SignupCategorySetActivity.kt
  app/src/main/java/com/unionz/bokzip/sign/SignupLocationSetActivity.kt
  app/src/main/res/drawable/btn_search_box_bg.xml
  app/src/main/res/drawable/hyperlink_underline.xml
  app/src/main/res/drawable/ic_detail.xml
  app/src/main/res/drawable/ic_prev_step.xml
  app/src/main/res/drawable/rounding_img.xml
  app/src/main/res/layout/activity_detail.xml
  app/src/main/res/layout/activity_intro.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_my.xml
  app/src/main/res/layout/activity_search.xml
  app/src/main/res/layout/activity_search_result.xml
  app/src/main/res/layout/activity_signin.xml
  app/src/main/res/layout/activity_signup_category_set.xml
  app/src/main/res/layout/activity_signup_location_set.xml
  app/src/main/res/layout/bottom_sheet_filter.xml
  app/src/main/res/layout/filter_content_category.xml
  app/src/main/res/layout/filter_content_locaiton.xml
  app/src/main/res/layout/filter_content_sort.xml
  app/src/main/res/layout/fragment_tap_general.xml
  app/src/main/res/layout/fragment_tap_recommend.xml
  app/src/main/res/layout/fragment_tap_scrap.xml
  app/src/main/res/layout/item_bokji.xml
  app/src/main/res/layout/item_search.xml
  app/src/main/res/layout/item_tab.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: feat, 최영진

#7 [add:#2] 거주지 검색 결과 레이아웃 item_search_location.xml 추가
  app/src/main/res/layout/item_search_location.xml
Labels: 최영진, add

#9 [feat:#8] Tmap API 관련 코드 작성
  .gitignore
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/unionz/bokzip/model/AddressInfo.kt
  app/src/main/java/com/unionz/bokzip/model/AddressInfoResponse.kt
  app/src/main/java/com/unionz/bokzip/model/Poi.kt
  app/src/main/java/com/unionz/bokzip/model/Pois.kt
  app/src/main/java/com/unionz/bokzip/model/SearchPoiInfo.kt
  app/src/main/java/com/unionz/bokzip/model/SearchResponse.kt
  app/src/main/java/com/unionz/bokzip/model/SearchResultEntity.kt
  app/src/main/java/com/unionz/bokzip/service/ApiService.kt
  app/src/main/java/com/unionz/bokzip/util/RetrofitUtil.kt
  app/src/main/java/com/unionz/bokzip/util/Url.kt
Labels: feat, 최영진, search

#10 [mod] tools:text -> android:text로 변경
  app/src/main/res/layout/bottom_sheet_filter.xml
Labels: 최영진, ui, mod

#15 [feat:#6]필터 구현
  app/build.gradle
  app/src/main/java/com/unionz/bokzip/FilterBottomSheet.kt
  app/src/main/java/com/unionz/bokzip/home/MainActivity.kt
  app/src/main/java/com/unionz/bokzip/home/RecommendFragment.kt
  app/src/main/res/drawable/selector_category_bg.xml
  app/src/main/res/drawable/selector_category_text_color.xml
  app/src/main/res/layout/bottom_sheet_filter.xml
Labels: feat, 이은지, filter
