Repository bokzip/bokzip-android, pull requests merged in 2021-09, with the labels that each got.

#19 [feat : #6]필터 구현
  .idea/misc.xml
  .idea/runConfigurations.xml
  app/src/main/java/com/unionz/bokzip/AutoCompleteParse.kt
  app/src/main/java/com/unionz/bokzip/FilterBottomSheet.kt
  app/src/main/java/com/unionz/bokzip/TMapSearchInfo.kt
  app/src/main/java/com/unionz/bokzip/adapter/LocationItemAdapter.kt
  app/src/main/java/com/unionz/bokzip/home/RecommendFragment.kt
  app/src/main/java/com/unionz/bokzip/model/LocationItem.kt
  app/src/main/java/com/unionz/bokzip/model/Poi.kt
  app/src/main/java/com/unionz/bokzip/model/Pois.kt
  app/src/main/java/com/unionz/bokzip/model/SearchPoiInfo.kt
  app/src/main/res/layout/bottom_sheet_filter.xml
Labels: feat, 이은지, filter

#21 [feat:#20] 스크랩 DB연동
  app/src/main/java/com/unionz/bokzip/DetailActivity.kt
  app/src/main/java/com/unionz/bokzip/adapter/GeneralBokjiItemAdapter.kt
  app/src/main/java/com/unionz/bokzip/adapter/RecommendBokjiItemAdapter.kt
  app/src/main/java/com/unionz/bokzip/service/RemoteLib.kt
  app/src/main/java/com/unionz/bokzip/service/RemoteService.kt
Labels: feat, 최영진, db, scrap

#22 [feat:#20] 스크랩 시 메인화면 데이터 갱신 및 조회수 증가 구현
  app/src/main/java/com/unionz/bokzip/DetailActivity.kt
  app/src/main/java/com/unionz/bokzip/GeneralDetaillActivity.kt
  app/src/main/java/com/unionz/bokzip/home/GeneralFragment.kt
  app/src/main/java/com/unionz/bokzip/home/RecommendFragment.kt
  app/src/main/java/com/unionz/bokzip/service/RemoteService.kt
  app/src/main/java/com/unionz/bokzip/util/PreferenceUtil.kt
Labels: feat, 최영진, scrap

#23 [mod] 테스트용 코드 삭제 및 pref 수정
  app/src/main/java/com/unionz/bokzip/FilterBottomSheet.kt
  app/src/main/java/com/unionz/bokzip/MyActivity.kt
  app/src/main/java/com/unionz/bokzip/home/MainActivity.kt
  app/src/main/java/com/unionz/bokzip/home/RecommendFragment.kt
  app/src/main/java/com/unionz/bokzip/sign/SigninActivity.kt
  app/src/main/java/com/unionz/bokzip/util/PreferenceUtil.kt
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/activity_my.xml
Labels: mod
